# Dokumentation für die Azure Web Apps Deploy Action: https://github.com/Azure/webapps-deploy
# Weitere GitHub Actions für Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Layer2AufgabeServer20240911164841

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1' # Setze hier die verwendete .NET Version

      - name: Build Server Project
        run: dotnet build Layer2Aufgabe/Layer2Aufgabe.Server/Layer2Aufgabe.Server.csproj --configuration Release

      - name: Publish Server Project
        run: dotnet publish Layer2Aufgabe/Layer2Aufgabe.Server/Layer2Aufgabe.Server.csproj -c Release -o ./publish/server

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Setze hier die verwendete Node.js Version für das Client-Projekt

      - name: Install Client Dependencies
        working-directory: Layer2Aufgabe/layer2aufgabe.client
        run: npm install

      - name: Build Client Project
        working-directory: Layer2Aufgabe/layer2aufgabe.client
        run: npm run build

      - name: Move Client Build to Publish Directory
        run: |
          mkdir -p ./publish/client
          cp -R Layer2Aufgabe/layer2aufgabe.client/dist/* ./publish/client

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Erforderlich für JWT-Authentifizierung

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy Server to Azure Web App
        id: deploy-server
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Layer2AufgabeServer20240911164841' # Name der Azure Web App für den Server
          slot-name: 'Production'
          package: ./publish/server

      - name: Deploy Client to Azure Web App
        id: deploy-client
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Layer2AufgabeClient20240911164841' # Name der Azure Web App für den Client
          slot-name: 'Production'
          package: ./publish/client
