name: Build and deploy ASP.Net Core app to Azure Web App - Layer2AufgabeServer20240911164841

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'

      # Build and publish the Server app
      - name: Build Server
        run: dotnet build Layer2Aufgabe.Server/Layer2Aufgabe.Server.csproj --configuration Release

      - name: Publish Server
        run: dotnet publish Layer2Aufgabe.Server/Layer2Aufgabe.Server.csproj -c Release -o ./publish/server

      # Upload the server artifact
      - name: Upload Server Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: server-app
          path: ./publish/server

      # Build and publish the Client app
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build Client
        working-directory: ./layer2aufgabe.client
        run: |
          npm install
          npm run build

      - name: Publish Client
        run: |
          mkdir -p ./publish/client
          cp -r ./layer2aufgabe.client/dist/* ./publish/client

      # Upload the client artifact
      - name: Upload Client Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: ./publish/client

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download Server Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: server-app
          path: ./publish/server

      - name: Download Client Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: client-app
          path: ./publish/client

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy both Client and Server to the same Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Layer2AufgabeServer20240911164841'  # Name der Web App des Servers verwenden
          slot-name: 'Production'
          package: ./publish
